datasources:
  default:
    url: jdbc:tc:postgresql:9.6.8:///databasename
    dbCreate: create-update
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
jpa:
  default:
    entity-scan:
      packages:
        - 'com.example.galaksiya.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
