micronaut:
  application:
    name: demo
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/London
    driverClassName: org.postgresql.Driver
    username: administrator
    password: 'ersin'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    packages-to-scan:
      - "com.example.galaksiya.model"
    properties:
      hibernate:
        show_sql: false
netty:
  default:
    allocator:
      max-order: 3
rabbitmq.uri: amqp://localhost:5672




